### ISSUE TITLE
Backend 모델 및 뷰 수정 건의

### ISSUE THREAD

**Issue by Whiteppanda** [swsnu/swppfall2022-team18#19]
1. Sign up시 해당 user에 딸린 Closet까지 함께 생성하도록 수정: signup 함수 수정 
2. UserCloth 모델 pattern field가 null을 허용하지 않는 것으로 보임. null 허용하도록 수정

**Comment by engineerA314** [comment]
1은 맞는데 2는 안될거같음. 대신 "None" 을 저장하도록 하는게 나을듯
