### ISSUE TITLE
post 를 이용한 outfit filter 관련 api 통합 구현

### ISSUE THREAD

**Issue by engineerA314** [swsnu/swppfall2022-team18#21]
sprint 2 때는 outfit page의 filter 관련 기능을 구현할 때, 각 filter 종류에 따라 다른 get api를 구현해서 이를 사용하는 것이 계획이었는데, 이는 프론트에서 api를 사용하기도 어렵고, 백에서 여러 종류의 filter가 동시에 요구되었을 때 이를 처리하기도 어려운 것 같음

따라서 실제로는 GET api의 역할을 하지만 (db 정보를 변화시키지 않고 정보를 가져오기만 하기 때문에), POST api를 사용해 request.body에 필터 관련 정보를 집어넣어 주고받는 방식으로 이를 구현하고자 함

따라서 
-필터링된 정보와 outfit 전체 정보를 가져오는 api를 `outfit/` url로 통합
- 전체 정보를 원할 때는 GET, 필터링된 정보를 원할때는 POST를 사용하되, POST에 필터링 정보를 비워서 보내면 GET과 같은 동작을 하도록 구현할 예정

POST에 담아줘야 하는 Request Body는 다음과 같음
```
{
    'type': 'type1',
    'color': 'color1',
    'pattern': 'pattern1',
    'userHave': 'False',
    'recommend': 'False'
}
```
userHave는 유저가 가지고 있는 옷을 포함하는 코디, recommend는 유저가 바로 입을 수 있는 코디를 요청하는 정보로 True 또는 False를 가질 수 있음
또 두 정보중 하나가 True라면 다른 한 쪽은 반드시 False 여야 함.
옷 종류에 관한 필터 정보는 비어있을 수는 있으나 `'type': ''` 와 같은 형태로 주어져야 함.

이 POST API 의 response.content 는 다음과 같음

```
{
            'type': filter_type,
            'color': filter_color,
            'pattern': filter_pattern,
            'useLabelSet': using_labelset (유저가 요청한 필터를 합한 것과 같은 labelset object 가 db에 존재하는지 여부),
            'userHave': filter_userhave,
            'recommend': filter_recommend,
            'isLast': is_last,
            'cursor': newCursor,
            'outfits': [
...
]
        }
```

**Comment by Whiteppanda** [comment]
음 이거 그 GET request로 구현하는게 더 편하지 않을까? 
type, color, pattern, false, recommend에 대한 default 값을 두고 여기서 GET으로 보내오는 url에 따라서 보내주는 형식으로?
