### ISSUE TITLE
backend usercloth dates 관련 api issue

### ISSUE THREAD

**Issue by engineerA314** [swsnu/swppfall2022-team18#42]
closet_item의 POST는 오늘 날짜를 body로 받아서 그걸 dates에 추가시켜주는 기능이고, PUT은 usercloth 하나의 정보를 마음대로 바꿀 수 있는 기능임.

따라서 옷을 입었다고 front에서 버튼을 클릭했을 경우에는 POST를 불러야 하지만, 같은 버튼을 다시 눌러서 옷을 입지 않았다고 정보를 수정할 때는 PUT을 불러야 하는데, 이게 애매한 것 같음.

그래서 날짜 정보 자체는 백엔드에서 today() 함수를 이용해서 처리할 수 있으니까, POST에 true/false boolean 값을 하나 넣어서 옷을 입은 것으로 변경/ 안 입은 것으로 변경 두 가지 기능을 동시에 수행하게 만드는 것은 어떨까 싶음.

이렇게 구현할 경우 각 usercloth detail 페이지에서의 옷 입음 체크 버튼이나, 메인 페이지에서 오늘의 추천 코디 입기 결정 버튼을 구현할 때 더 쉬울 수도 있을 듯.

**Comment by lukaspark16** [comment]
이거 위에 링크된 pr에서 해결됐나? 아니면 새로운 작업으로 진행할게~

**Comment by lukaspark16** [comment]
바로 다음에 올라갈 커밋에서 해결했음!
