### ISSUE TITLE
AddClothModal 과 FilterModal 에서의 color filter option의 시각적 구현

### ISSUE THREAD

**Issue by engineerA314** [swsnu/swppfall2022-team18#64]
- 색상 필터의 경우 선택지가 35개로 너무 많고, 색상은 이름만으로 어떤 색인지 파악하기가 쉽지 않음.

- 따라서 6*6 형태의 색상 표를 select option으로 띄운 다음에 마우스가 hover 할 때 색의 이름을 띄우는 방식으로 filter option을 구현하는 것이 바람직할 것 같음

(현재 type의 경우에는 트리 구조를 이용해서 2단계의 option으로 최종 tag를 선택하도록 구현하였음. 색도 이런 방식으로 구현하는 것도 가능은 할 듯)

**Comment by lukaspark16** [comment]
확인~

**Comment by lukaspark16** [comment]
react color 사용하여 처리
