### ISSUE TITLE
Frontend Test LocalStorage mocking 도입 필요

### ISSUE THREAD

**Issue by engineerA314** [swsnu/swppfall2022-team18#65]
Home, Outfit, Closet, OutfitDetail 페이지 모두 checkLoginned() 함수를 이용한 로그인 확인 및 리다이렉트 기능이 존재함
이 기능을 테스트하기 위해서는 LocalStorage 에 대한 mocking이 필요하고, 한 번만 구현되면 모든 페이지의 test에서 사용가능함.

**Comment by Whiteppanda** [comment]
다음 sprint 까지 완성할게요~
