### ISSUE TITLE
Outfit Page 추가 기능 구현 여부

### ISSUE THREAD

**Issue by engineerA314** [swsnu/swppfall2022-team18#66]
유저 편의성을 위해 Outfit Page 에서 적용가능한 각 cloth tag filter에 대해 현재 내용을 화면에 출력하고 독립적으로 제거가 가능하도록 구현하는 것이 어떨까 싶음.

구현한다면 다음 sprint 5에서 구현해야 하는데, ML feature 적용과 우선도를 비교하여 구현 여부를 결정해야 함.

**Comment by Whiteppanda** [comment]
'현재 내용을 화면에 출력하고 독립적으로 제거가 가능하도록 구현하는 것이 어떨까 싶음.'
이 부분이 정확이 뭔지 이해가 안감

**Comment by engineerA314** [comment]
![스크린샷, 2022-11-30 15-27-52](https://user-images.githubusercontent.com/86403521/204723820-d033aaca-6c10-40b2-a72b-2d551908106c.png)
@Whiteppanda 이런 식으로 현재 설정된 필터 내용을 표시한다는 뜻이야.
구현 했고 pr 올릴게
