### ISSUE TITLE
ClothDetailModal -> Outfit Page 이동 관련 구현

### ISSUE THREAD

**Issue by engineerA314** [swsnu/swppfall2022-team18#67]
ClothDetailModal 에서 Outfit Page 로 이동할 때에는 현재 화면에 띄우고 있는 UserCloth의 Labelset 정보를 store outfit.filter에 입력하거나, Outfit 의 props 에 입력한 상태로 Outfit Page로 이동해야 함.

이를 위해서는 outfit.ts 의 editFilter reducer 가 사용되어야 함.

**Comment by lukaspark16** [comment]
아하 확인~
